import type { Metadata } from "next"
import { ThemeProvider } from "@/providers/ThemeProvider"
import { GeistSans } from "geist/font/sans"
import { Toaster } from "sonner"

import { cn } from "@/lib/utils"
import { TailwindIndicator } from "@/components/TailwindIndicator"

import "./globals.css"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head />
      <body
        className={cn(
          "bg-background min-h-screen scroll-smooth antialiased",
          GeistSans.className
        )}
      >
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <div className="relative flex min-h-screen flex-col">
            <div className="flex-1">{children}</div>
          </div>
          <TailwindIndicator />

          <Toaster position="top-right" richColors />
        </ThemeProvider>
      </body>
    </html>
  )
}
